[theme]
primaryColor = "#1F2937"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F9FAFB"
textColor = "#111827"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
